#!/bin/bash

echo "🚀 Backend Deployment to Railway"
echo "================================"
echo ""
echo "Since GitHub auth is tricky, here's the fastest way:"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Sign up/Login"
echo "3. Click 'New Project' -> 'Empty Project'"
echo "4. Click 'Deploy from GitHub repo' (try again with the repo)"
echo "5. OR use Railway CLI:"
echo ""
echo "   npm install -g @railway/cli"
echo "   railway login"
echo "   cd backend"
echo "   railway init"
echo "   railway up"
echo ""
echo "6. Copy your Railway URL when it's deployed"
echo ""
echo "🎯 Your backend will be at: https://your-service.up.railway.app"
echo ""
echo "Then update your Vercel app with:"
echo "NEXT_PUBLIC_API_URL=https://your-railway-url" 